// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PromptTasks.Infrastructure.Persistence;

#nullable disable

namespace PromptTasks.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260604014137_AddWorkflowPhaseRoles")]
    partial class AddWorkflowPhaseRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PromptTasks.Domain.Ai.AiChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("CachedTokens")
                        .HasColumnType("integer");

                    b.Property<int?>("CandidateTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Sequence");

                    b.ToTable("ai_chat_messages", (string)null);
                });

            modelBuilder.Entity("PromptTasks.Domain.Ai.AiChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CacheExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CacheSystemInstructionHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("CachedThroughSequence")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeminiCacheName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PromptId")
                        .HasColumnType("uuid");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<int?>("ThinkingBudget")
                        .HasColumnType("integer");

                    b.Property<bool>("ThinkingEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ThinkingLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WorkingDirectoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PromptId");

                    b.HasIndex("OwnerId", "UpdatedAtUtc");

                    b.ToTable("ai_chat_sessions", (string)null);
                });

            modelBuilder.Entity("PromptTasks.Domain.Ai.AiUserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<int?>("ThinkingBudget")
                        .HasColumnType("integer");

                    b.Property<bool>("ThinkingEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ThinkingLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("ai_user_settings", (string)null);
                });

            modelBuilder.Entity("PromptTasks.Domain.Prompts.DailyTaskSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("SequenceDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkingDirectoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkingDirectoryId", "SequenceDate")
                        .IsUnique();

                    b.ToTable("daily_task_sequences", (string)null);
                });

            modelBuilder.Entity("PromptTasks.Domain.Prompts.LinkedDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AbsolutePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("AbsolutePathKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer");

                    b.Property<string>("LastContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PromptId")
                        .HasColumnType("uuid");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WorkingDirectoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("WorkingDirectoryId");

                    b.HasIndex("PromptId", "AbsolutePathKey")
                        .IsUnique();

                    b.ToTable("linked_documents", (string)null);
                });

            modelBuilder.Entity("PromptTasks.Domain.Prompts.LinkedDocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LinkedDocumentId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LinkedDocumentId", "CreatedAtUtc");

                    b.HasIndex("LinkedDocumentId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("linked_document_versions", (string)null);
                });

            modelBuilder.Entity("PromptTasks.Domain.Prompts.Prompt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentPromptId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TargetAgent")
                        .HasColumnType("integer");

                    b.Property<string>("TaskNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkingDirectoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentPromptId", "UpdatedAtUtc");

                    b.HasIndex("WorkingDirectoryId", "Status");

                    b.HasIndex("WorkingDirectoryId", "TaskNumber")
                        .IsUnique()
                        .HasFilter("\"TaskNumber\" IS NOT NULL");

                    b.HasIndex("WorkingDirectoryId", "UpdatedAtUtc");

                    b.ToTable("prompts", (string)null);
                });

            modelBuilder.Entity("PromptTasks.Domain.Prompts.PromptFileReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Exists")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PromptId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawMention")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PromptId", "RelativePath")
                        .IsUnique();

                    b.ToTable("prompt_file_references", (string)null);
                });

            modelBuilder.Entity("PromptTasks.Domain.Prompts.PromptVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid>("PromptId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TargetAgent")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PromptId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("prompt_versions", (string)null);
                });

            modelBuilder.Entity("PromptTasks.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PromptTasks.Domain.Workflows.PromptWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CurrentActor")
                        .HasColumnType("integer");

                    b.Property<string>("CurrentPhaseColor")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("CurrentPhaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentPhaseIteration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("CurrentPhaseName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("EnteredCurrentPhaseAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PromptId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PromptId")
                        .IsUnique();

                    b.ToTable("prompt_workflows", (string)null);
                });

            modelBuilder.Entity("PromptTasks.Domain.Workflows.PromptWorkflowEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("Actor")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PhaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhaseNameSnapshot")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("PromptWorkflowId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PromptWorkflowId", "OccurredAtUtc");

                    b.ToTable("prompt_workflow_events", (string)null);
                });

            modelBuilder.Entity("PromptTasks.Domain.Workflows.PromptWorkflowPhase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("DefaultActor")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("PromptWorkflowId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PromptWorkflowId", "OrderIndex");

                    b.ToTable("prompt_workflow_phases", (string)null);
                });

            modelBuilder.Entity("PromptTasks.Domain.Workflows.WorkflowTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("workflow_templates", (string)null);
                });

            modelBuilder.Entity("PromptTasks.Domain.Workflows.WorkflowTemplatePhase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("DefaultActor")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int?>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowTemplateId", "OrderIndex");

                    b.ToTable("workflow_template_phases", (string)null);
                });

            modelBuilder.Entity("PromptTasks.Domain.WorkingDirectories.WorkingDirectory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AbsolutePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EnableAiContext")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RespectGitignore")
                        .HasColumnType("boolean");

                    b.Property<string>("TaskNumberPattern")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "AbsolutePath")
                        .IsUnique();

                    b.ToTable("working_directories", (string)null);
                });

            modelBuilder.Entity("PromptTasks.Domain.Ai.AiChatMessage", b =>
                {
                    b.HasOne("PromptTasks.Domain.Ai.AiChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("PromptTasks.Domain.Prompts.DailyTaskSequence", b =>
                {
                    b.HasOne("PromptTasks.Domain.WorkingDirectories.WorkingDirectory", "WorkingDirectory")
                        .WithMany()
                        .HasForeignKey("WorkingDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkingDirectory");
                });

            modelBuilder.Entity("PromptTasks.Domain.Prompts.LinkedDocument", b =>
                {
                    b.HasOne("PromptTasks.Domain.Prompts.Prompt", "Prompt")
                        .WithMany("LinkedDocuments")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PromptTasks.Domain.WorkingDirectories.WorkingDirectory", "WorkingDirectory")
                        .WithMany()
                        .HasForeignKey("WorkingDirectoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Prompt");

                    b.Navigation("WorkingDirectory");
                });

            modelBuilder.Entity("PromptTasks.Domain.Prompts.LinkedDocumentVersion", b =>
                {
                    b.HasOne("PromptTasks.Domain.Prompts.LinkedDocument", "LinkedDocument")
                        .WithMany("Versions")
                        .HasForeignKey("LinkedDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedDocument");
                });

            modelBuilder.Entity("PromptTasks.Domain.Prompts.Prompt", b =>
                {
                    b.HasOne("PromptTasks.Domain.Users.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PromptTasks.Domain.Prompts.Prompt", "ParentPrompt")
                        .WithMany("ChildPrompts")
                        .HasForeignKey("ParentPromptId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PromptTasks.Domain.WorkingDirectories.WorkingDirectory", "WorkingDirectory")
                        .WithMany("Prompts")
                        .HasForeignKey("WorkingDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("ParentPrompt");

                    b.Navigation("WorkingDirectory");
                });

            modelBuilder.Entity("PromptTasks.Domain.Prompts.PromptFileReference", b =>
                {
                    b.HasOne("PromptTasks.Domain.Prompts.Prompt", "Prompt")
                        .WithMany("FileReferences")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("PromptTasks.Domain.Prompts.PromptVersion", b =>
                {
                    b.HasOne("PromptTasks.Domain.Prompts.Prompt", "Prompt")
                        .WithMany("Versions")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("PromptTasks.Domain.Workflows.PromptWorkflow", b =>
                {
                    b.HasOne("PromptTasks.Domain.Prompts.Prompt", "Prompt")
                        .WithOne()
                        .HasForeignKey("PromptTasks.Domain.Workflows.PromptWorkflow", "PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("PromptTasks.Domain.Workflows.PromptWorkflowEvent", b =>
                {
                    b.HasOne("PromptTasks.Domain.Workflows.PromptWorkflow", "Workflow")
                        .WithMany("Events")
                        .HasForeignKey("PromptWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("PromptTasks.Domain.Workflows.PromptWorkflowPhase", b =>
                {
                    b.HasOne("PromptTasks.Domain.Workflows.PromptWorkflow", "Workflow")
                        .WithMany("Phases")
                        .HasForeignKey("PromptWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("PromptTasks.Domain.Workflows.WorkflowTemplate", b =>
                {
                    b.HasOne("PromptTasks.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PromptTasks.Domain.Workflows.WorkflowTemplatePhase", b =>
                {
                    b.HasOne("PromptTasks.Domain.Workflows.WorkflowTemplate", "Template")
                        .WithMany("Phases")
                        .HasForeignKey("WorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("PromptTasks.Domain.WorkingDirectories.WorkingDirectory", b =>
                {
                    b.HasOne("PromptTasks.Domain.Users.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PromptTasks.Domain.Ai.AiChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PromptTasks.Domain.Prompts.LinkedDocument", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PromptTasks.Domain.Prompts.Prompt", b =>
                {
                    b.Navigation("ChildPrompts");

                    b.Navigation("FileReferences");

                    b.Navigation("LinkedDocuments");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PromptTasks.Domain.Workflows.PromptWorkflow", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Phases");
                });

            modelBuilder.Entity("PromptTasks.Domain.Workflows.WorkflowTemplate", b =>
                {
                    b.Navigation("Phases");
                });

            modelBuilder.Entity("PromptTasks.Domain.WorkingDirectories.WorkingDirectory", b =>
                {
                    b.Navigation("Prompts");
                });
#pragma warning restore 612, 618
        }
    }
}
