/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces/index'
import { Route as WorkspacesWorkspaceIdRouteImport } from './routes/workspaces/$workspaceId'
import { Route as WorkspacesWorkspaceIdIndexRouteImport } from './routes/workspaces/$workspaceId/index'
import { Route as WorkspacesWorkspaceIdFilesRouteImport } from './routes/workspaces/$workspaceId/files'
import { Route as WorkspacesWorkspaceIdTasksTaskNumberRouteImport } from './routes/workspaces/$workspaceId/tasks/$taskNumber'
import { Route as WorkspacesWorkspaceIdPromptsNewRouteImport } from './routes/workspaces/$workspaceId/prompts/new'
import { Route as WorkspacesWorkspaceIdPromptsPromptIdRouteImport } from './routes/workspaces/$workspaceId/prompts/$promptId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdRouteImport.update({
  id: '/workspaces/$workspaceId',
  path: '/workspaces/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdIndexRoute =
  WorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdFilesRoute =
  WorkspacesWorkspaceIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdTasksTaskNumberRoute =
  WorkspacesWorkspaceIdTasksTaskNumberRouteImport.update({
    id: '/tasks/$taskNumber',
    path: '/tasks/$taskNumber',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdPromptsNewRoute =
  WorkspacesWorkspaceIdPromptsNewRouteImport.update({
    id: '/prompts/new',
    path: '/prompts/new',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdPromptsPromptIdRoute =
  WorkspacesWorkspaceIdPromptsPromptIdRouteImport.update({
    id: '/prompts/$promptId',
    path: '/prompts/$promptId',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteWithChildren
  '/workspaces/': typeof WorkspacesIndexRoute
  '/workspaces/$workspaceId/files': typeof WorkspacesWorkspaceIdFilesRoute
  '/workspaces/$workspaceId/': typeof WorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/prompts/$promptId': typeof WorkspacesWorkspaceIdPromptsPromptIdRoute
  '/workspaces/$workspaceId/prompts/new': typeof WorkspacesWorkspaceIdPromptsNewRoute
  '/workspaces/$workspaceId/tasks/$taskNumber': typeof WorkspacesWorkspaceIdTasksTaskNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/workspaces': typeof WorkspacesIndexRoute
  '/workspaces/$workspaceId/files': typeof WorkspacesWorkspaceIdFilesRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/prompts/$promptId': typeof WorkspacesWorkspaceIdPromptsPromptIdRoute
  '/workspaces/$workspaceId/prompts/new': typeof WorkspacesWorkspaceIdPromptsNewRoute
  '/workspaces/$workspaceId/tasks/$taskNumber': typeof WorkspacesWorkspaceIdTasksTaskNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteWithChildren
  '/workspaces/': typeof WorkspacesIndexRoute
  '/workspaces/$workspaceId/files': typeof WorkspacesWorkspaceIdFilesRoute
  '/workspaces/$workspaceId/': typeof WorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/prompts/$promptId': typeof WorkspacesWorkspaceIdPromptsPromptIdRoute
  '/workspaces/$workspaceId/prompts/new': typeof WorkspacesWorkspaceIdPromptsNewRoute
  '/workspaces/$workspaceId/tasks/$taskNumber': typeof WorkspacesWorkspaceIdTasksTaskNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/workspaces/$workspaceId'
    | '/workspaces/'
    | '/workspaces/$workspaceId/files'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/prompts/$promptId'
    | '/workspaces/$workspaceId/prompts/new'
    | '/workspaces/$workspaceId/tasks/$taskNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/workspaces'
    | '/workspaces/$workspaceId/files'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/prompts/$promptId'
    | '/workspaces/$workspaceId/prompts/new'
    | '/workspaces/$workspaceId/tasks/$taskNumber'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/workspaces/$workspaceId'
    | '/workspaces/'
    | '/workspaces/$workspaceId/files'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/prompts/$promptId'
    | '/workspaces/$workspaceId/prompts/new'
    | '/workspaces/$workspaceId/tasks/$taskNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  WorkspacesWorkspaceIdRoute: typeof WorkspacesWorkspaceIdRouteWithChildren
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId': {
      id: '/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId/': {
      id: '/workspaces/$workspaceId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof WorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/files': {
      id: '/workspaces/$workspaceId/files'
      path: '/files'
      fullPath: '/workspaces/$workspaceId/files'
      preLoaderRoute: typeof WorkspacesWorkspaceIdFilesRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/tasks/$taskNumber': {
      id: '/workspaces/$workspaceId/tasks/$taskNumber'
      path: '/tasks/$taskNumber'
      fullPath: '/workspaces/$workspaceId/tasks/$taskNumber'
      preLoaderRoute: typeof WorkspacesWorkspaceIdTasksTaskNumberRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/prompts/new': {
      id: '/workspaces/$workspaceId/prompts/new'
      path: '/prompts/new'
      fullPath: '/workspaces/$workspaceId/prompts/new'
      preLoaderRoute: typeof WorkspacesWorkspaceIdPromptsNewRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/prompts/$promptId': {
      id: '/workspaces/$workspaceId/prompts/$promptId'
      path: '/prompts/$promptId'
      fullPath: '/workspaces/$workspaceId/prompts/$promptId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdPromptsPromptIdRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
  }
}

interface WorkspacesWorkspaceIdRouteChildren {
  WorkspacesWorkspaceIdFilesRoute: typeof WorkspacesWorkspaceIdFilesRoute
  WorkspacesWorkspaceIdIndexRoute: typeof WorkspacesWorkspaceIdIndexRoute
  WorkspacesWorkspaceIdPromptsPromptIdRoute: typeof WorkspacesWorkspaceIdPromptsPromptIdRoute
  WorkspacesWorkspaceIdPromptsNewRoute: typeof WorkspacesWorkspaceIdPromptsNewRoute
  WorkspacesWorkspaceIdTasksTaskNumberRoute: typeof WorkspacesWorkspaceIdTasksTaskNumberRoute
}

const WorkspacesWorkspaceIdRouteChildren: WorkspacesWorkspaceIdRouteChildren = {
  WorkspacesWorkspaceIdFilesRoute: WorkspacesWorkspaceIdFilesRoute,
  WorkspacesWorkspaceIdIndexRoute: WorkspacesWorkspaceIdIndexRoute,
  WorkspacesWorkspaceIdPromptsPromptIdRoute:
    WorkspacesWorkspaceIdPromptsPromptIdRoute,
  WorkspacesWorkspaceIdPromptsNewRoute: WorkspacesWorkspaceIdPromptsNewRoute,
  WorkspacesWorkspaceIdTasksTaskNumberRoute:
    WorkspacesWorkspaceIdTasksTaskNumberRoute,
}

const WorkspacesWorkspaceIdRouteWithChildren =
  WorkspacesWorkspaceIdRoute._addFileChildren(
    WorkspacesWorkspaceIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  WorkspacesWorkspaceIdRoute: WorkspacesWorkspaceIdRouteWithChildren,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
